FROM node:19-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM stefangeorgesco/nginx-auth-ssl

COPY --from=build /app/dist /usr/share/nginx/html/dmp
