# image : stefangeorgesco/dmp-oauth-frontend

FROM node:16.16.0-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html/dmp

COPY templates/. /etc/nginx/templates

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]